### PR TITLE
deleted:    tests/unit-fail-compilation/kcc_config

### PR DESCRIPTION
**Pull request by charala1**

### CODE REVIEW

**Comment by dwightguth** [comment]
can we put files with this name in .gitignore too?

**Comment by charala1** [comment]
Done!

**Comment by chathhorn** [comment]
This was added to prevent differences in error messages depending on whether that file was produced or not. It might not be needed anymore because I think we're chopping that line now anyway, but please verify locally -- these tests are run on rv-match, not in the c-sem pr job.

**Comment by charala1** [comment]
> This was added to prevent differences in error messages depending on whether that file was produced or not. It might not be needed anymore because I think we're chopping that line now anyway, but please verify locally -- these tests are run on rv-match, not in the c-sem pr job.

@chathhorn what should I verify then? That the file is not produced, or something else?

**Comment by charala1** [comment]
Closing in favor of issue https://github.com/kframework/c-semantics/issues/492

**Pull request closed without merging**
