### PR TITLE
fixed cleanup before return

### PR DESCRIPTION
**Pull request by andreistefanescu**

### CODE REVIEW

**Comment by andreistefanescu** [comment]
@dwightguth @chathhorn please review

**Comment by dwightguth** [comment]
I'm kinda surprised this passes all the tests and doesn't degrade the quality of the error messages, but since it does, lgtm.

**Comment by andreistefanescu** [comment]
@dwightguth why are you surprised?

**Comment by dwightguth** [comment]
well I would have thought that deleting the objects at the end of the block would have consequences for code that is trying to determine whether an object is currently live.

**Comment by andreistefanescu** [comment]
the previous code was also deleting the objects, but I think is was less clear what was happening.

**Comment by dwightguth** [comment]
Oh I see. I misread the change then. yeah, this seems fine

**Comment by chathhorn** [comment]
Looks fine.

**Pull request merged**
