### PR TITLE
Add many more error recovery cases + optimize KCC for RV-Match

### PR DESCRIPTION
**Pull request by dwightguth**
@chathhorn @andreistefanescu please review

### CODE REVIEW

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
@chathhorn @andreistefanescu please review

**Comment by andreistefanescu** [comment]
Looks good. Do you have any plans to make error recovery more modular, so the user can specify which type of errors to recover from?

**Comment by dwightguth** [comment]
I don't specifically have plans to do that myself; I think ultimately we may want that type of behavior, however. Maybe have Chris work on it at the same time as he works on the separation of the positive and negative semantics?

**Comment by andreistefanescu** [comment]
I don't have any designs in this direction now. We can talk about it when the need arises.

**Comment by chathhorn** [comment]
Looks good!

**Pull request merged**
