### PR TITLE
Clang type inference

### PR DESCRIPTION
**Pull request by chathhorn**
- Passes template instantiations & type of `auto` decls deduced by clang to the C++ translation semantics.
- Removes template deduction and the `CPPTypeExpr` sort from the C++ semantics.

### CODE REVIEW

**Comment by chathhorn** [comment]
@dwightguth please review when you get the chance.

**Comment by dwightguth** [comment]
I didn't look in depth at the changes to the semantics, so you should still get someone else to review, but this looks good from my perspective.

**Comment by chathhorn** [comment]
@h0nzZik please review when you get the chance.

**Comment by h0nzZik** [comment]
Do we want to remove all the code? What if we will want to have semantics for templates in the future?

**Pull request merged**
