### PR TITLE
Refactoring of qualified types.

### PR DESCRIPTION
**Pull request by chathhorn**
This is meant to make a cleaner distinction between unqualifed and qualified types, mostly by introducing a production (ut) for types without qualifiers.

@dwightguth please review.

### CODE REVIEW

**Comment by chathhorn** [comment]
Jenkins: test this please.

**Comment by chathhorn** [comment]
Jenkins: test this please.

**Comment by pdaian** [comment]
@chathhorn looks like it hit a timeout, because I was using that machine for other things at the same time.  Perhaps retest (not sure if I have perms, but let's try it: 
Jenkins: test this please. )?

I've increased the timeout from 20 mins to 30 to compensate for other projects potentially building on the machine (build takes 15 on an idle Jenkins, so timeout should definitely be above 30).

**Comment by pdaian** [comment]
Hmm, still timing out.  Let's try again, sorry about that:

Jenkins: test this please

**Comment by chathhorn** [comment]
It's probably something I did, I was having performance issues with this stuff (although it's a bit frustrating that my fixes seem to have made it worse).

**Comment by chathhorn** [comment]
It looks like it's just spinning at the very end until it times out. Is there still some process running or something?

**Comment by chathhorn** [comment]
Moving to rv-match repo.

**Pull request closed without merging**
